on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

env:
  AZURE_WEBAPP_NAME: rob-actions-cd-demo
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '12.x'

jobs:
  webapp-deploy:
    name: 📦 Webapp Deploy - ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: "https://${{ env.AZURE_WEBAPP_NAME }}-${{ inputs.environment }}.azurewebsites.net/"

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install
      run: |
        npm install
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        slot-name: ${{ inputs.environment }}
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v1.2
      with:
        # Check the following URLs one by one sequentially
        url: https://${{ env.AZURE_WEBAPP_NAME }}-${{ inputs.environment }}.azurewebsites.net/|https://${{ env.AZURE_WEBAPP_NAME }}-${{ inputs.environment }}.azurewebsites.net/user/rob-derosa
        follow-redirect: no # Optional, defaults to "no"
        max-attempts: 3 # Optional, defaults to 1
        retry-delay: 5s # Optional, only applicable to max-attempts > 1
